# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequencies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frequencies.proto',
  package='frequencies',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x66requencies.proto\x12\x0b\x66requencies\"-\n\rFrequencyBand\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\"J\n\x13\x46requencyAllocation\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0f\n\x07primary\x18\x02 \x01(\x08\x12\x11\n\tfootnotes\x18\x03 \x03(\t\"{\n\x18\x46requencyAllocationBlock\x12(\n\x04\x62\x61nd\x18\x01 \x01(\x0b\x32\x1a.frequencies.FrequencyBand\x12\x35\n\x0b\x61llocations\x18\x02 \x03(\x0b\x32 .frequencies.FrequencyAllocation\"\xc0\x01\n\x14\x46requencyAllocations\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x1a\n\rparent_region\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04year\x18\x04 \x01(\r\x12\x0c\n\x04meta\x18\x05 \x01(\x0c\x12@\n\x11\x61llocation_blocks\x18\x06 \x03(\x0b\x32%.frequencies.FrequencyAllocationBlockB\x10\n\x0e_parent_regionb\x06proto3'
)




_FREQUENCYBAND = _descriptor.Descriptor(
  name='FrequencyBand',
  full_name='frequencies.FrequencyBand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='frequencies.FrequencyBand.lower', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper', full_name='frequencies.FrequencyBand.upper', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=79,
)


_FREQUENCYALLOCATION = _descriptor.Descriptor(
  name='FrequencyAllocation',
  full_name='frequencies.FrequencyAllocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='frequencies.FrequencyAllocation.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='primary', full_name='frequencies.FrequencyAllocation.primary', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='footnotes', full_name='frequencies.FrequencyAllocation.footnotes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=155,
)


_FREQUENCYALLOCATIONBLOCK = _descriptor.Descriptor(
  name='FrequencyAllocationBlock',
  full_name='frequencies.FrequencyAllocationBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='band', full_name='frequencies.FrequencyAllocationBlock.band', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allocations', full_name='frequencies.FrequencyAllocationBlock.allocations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=280,
)


_FREQUENCYALLOCATIONS = _descriptor.Descriptor(
  name='FrequencyAllocations',
  full_name='frequencies.FrequencyAllocations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='frequencies.FrequencyAllocations.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='frequencies.FrequencyAllocations.region', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_region', full_name='frequencies.FrequencyAllocations.parent_region', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year', full_name='frequencies.FrequencyAllocations.year', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='frequencies.FrequencyAllocations.meta', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allocation_blocks', full_name='frequencies.FrequencyAllocations.allocation_blocks', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_parent_region', full_name='frequencies.FrequencyAllocations._parent_region',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=283,
  serialized_end=475,
)

_FREQUENCYALLOCATIONBLOCK.fields_by_name['band'].message_type = _FREQUENCYBAND
_FREQUENCYALLOCATIONBLOCK.fields_by_name['allocations'].message_type = _FREQUENCYALLOCATION
_FREQUENCYALLOCATIONS.fields_by_name['allocation_blocks'].message_type = _FREQUENCYALLOCATIONBLOCK
_FREQUENCYALLOCATIONS.oneofs_by_name['_parent_region'].fields.append(
  _FREQUENCYALLOCATIONS.fields_by_name['parent_region'])
_FREQUENCYALLOCATIONS.fields_by_name['parent_region'].containing_oneof = _FREQUENCYALLOCATIONS.oneofs_by_name['_parent_region']
DESCRIPTOR.message_types_by_name['FrequencyBand'] = _FREQUENCYBAND
DESCRIPTOR.message_types_by_name['FrequencyAllocation'] = _FREQUENCYALLOCATION
DESCRIPTOR.message_types_by_name['FrequencyAllocationBlock'] = _FREQUENCYALLOCATIONBLOCK
DESCRIPTOR.message_types_by_name['FrequencyAllocations'] = _FREQUENCYALLOCATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrequencyBand = _reflection.GeneratedProtocolMessageType('FrequencyBand', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYBAND,
  '__module__' : 'frequencies_pb2'
  # @@protoc_insertion_point(class_scope:frequencies.FrequencyBand)
  })
_sym_db.RegisterMessage(FrequencyBand)

FrequencyAllocation = _reflection.GeneratedProtocolMessageType('FrequencyAllocation', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYALLOCATION,
  '__module__' : 'frequencies_pb2'
  # @@protoc_insertion_point(class_scope:frequencies.FrequencyAllocation)
  })
_sym_db.RegisterMessage(FrequencyAllocation)

FrequencyAllocationBlock = _reflection.GeneratedProtocolMessageType('FrequencyAllocationBlock', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYALLOCATIONBLOCK,
  '__module__' : 'frequencies_pb2'
  # @@protoc_insertion_point(class_scope:frequencies.FrequencyAllocationBlock)
  })
_sym_db.RegisterMessage(FrequencyAllocationBlock)

FrequencyAllocations = _reflection.GeneratedProtocolMessageType('FrequencyAllocations', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYALLOCATIONS,
  '__module__' : 'frequencies_pb2'
  # @@protoc_insertion_point(class_scope:frequencies.FrequencyAllocations)
  })
_sym_db.RegisterMessage(FrequencyAllocations)


# @@protoc_insertion_point(module_scope)
